version: "3"
services:
  uvicorn-gunicorn:
    build:
      context: ./uvicorn-gunicorn/
      dockerfile: ./pypy-uvicorn-gunicorn-3.7-slim.dockerfile
    ports:
      - "5000:80"
  fastapi:
    build:
      context: ./fastapi/
      dockerfile: ./pypy-fastapi-3.7-slim.dockerfile
    ports:
      - "5001:80"
